### ISSUE TITLE
Hi, how fix this(windows)

### ISSUE THREAD

**Issue by Glisteroki** [botapiprivate/MagicEden-Mint-Bot#42]
line 101, in add_extension 
    raise IOError("Path to the extension doesn't exist") 
OSError: Path to the extension doesn't exist

**Comment by botapiprivate** [comment]
Hello, please verify that the Phantom.crx is present in the same directory as the file main.py. 
If there is indeed the file then please try and updating to the last version of the repository by downloading/cloning the repository again.
If this still does not work. Please send more details like a screenshot of the command prompt.
I hope this helps.

**Comment by Glisteroki** [comment]
![Uploading 54C49EBC-7818-478F-AAB9-547A9FD3A693.png…]()

**Comment by Glisteroki** [comment]
Don’t work

**Comment by botapiprivate** [comment]
I think there is an issue with the image you uploaded. Please wait until image has finished uploading

**Comment by Glisteroki** [comment]
![E4705B9E-5FC9-4B32-AEC4-8A505B467547](https://user-images.githubusercontent.com/98986855/152433731-000a3d66-0a2a-419f-9f77-1b8f2fcc1443.png)

**Comment by botapiprivate** [comment]
I'm looking into it, will comment back when i found the problem

**Comment by botapiprivate** [comment]
may i see the path your cmd is in ? It should look like this :
[](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzjnefuoQGTY&psig=AOvVaw2UL9fl9QDURsUMaR3RjnQ8&ust=1644011185186000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKCYk4nB5PUCFQAAAAAdAAAAABAD)

**Comment by botapiprivate** [comment]
Another possibility will be to replace inside `main.py` the following code
`options.add_extension("Phantom.crx")` line 123
by
`options.add_extension("C:/Users/username/Downloads/MagicEden-Mint-Bot/windows/Phantom.crx")`
of course use your own path for the file.

**Comment by Glisteroki** [comment]
Don’t help

**Comment by botapiprivate** [comment]
can i see by what did you replace 

> Another possibility will be to replace inside `main.py` the following code `options.add_extension("Phantom.crx")` line 123 by `options.add_extension("C:/Users/username/Downloads/MagicEden-Mint-Bot/windows/Phantom.crx")` of course use your own path for the file.

Can I see by what you replaced this ?
